name: SPD Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ios-comp:
   runs-on: macos-12
   steps:
     - uses: actions/checkout@v4
     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
          distribution: "temurin"
          java-version: 17

     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1.4.1
       with:
          xcode-version: 14.2
    
     - name: Build
       run: |
          git clone --depth=1 --recurse-submodules https://github.com/00-Evan/shattered-pixel-dungeon
          cd shattered-pixel-dungeon
          ls
          chmod +x ./gradlew
          ./gradlew --stacktrace build
          cd ..
     - uses: actions/upload-artifact@v4
       with:
        name: spd
        path: shattered-pixel-dungeon
