name: SPD Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ios-comp:
   runs-on: macos-12
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         repository: 00-Evan/shattered-pixel-dungeon
     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
          distribution: "temurin"
          java-version: 17

     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
     - name: Setup Xcode
       uses: maxim-lobanov/setup-xcode@v1.4.1
       with:
          xcode-version: 14.2
    
     - name: Build
       run: |
          ls
          chmod +x ./gradlew
          ./gradlew --stacktrace ios
